"""Bayesian prioritized replay sampler.

Combines a Normal-Gamma posterior over Q(s, a) (Dearden, Friedman & Russell
1998) with a Dirichlet posterior over transitions T(s'|s, a) (Dearden,
Friedman & Andre 1999) to drive simulated replay: rather than replaying only
transitions actually observed, candidate (s, a, s') backups are generated by
sampling from the agent's own uncertainty about the world, and prioritized
either by Thompson sampling or by Expected Value of Backup (Mattar & Daw
2018).

The overall idea is a version of the "Bayesian Mixture Modeling and Inference based Thomson
Sampling in Monte-Carlo Tree Search" by Aijun Bai et al. 2018. The idea being that
the tree search is used to look for replay trajectories that maximize EVB instead of planned trajectories
to maximize reward. This algorithm is sort of in between the chaining calculation in Marcelo's
paper and the tree search of Aijun.
"""
from __future__ import annotations

from typing import Literal
import numpy as np

from unc_pma.bayesian_qlearning import BayesianQLearning
from unc_pma.environment_model import DirichletTransitionsModel
from unc_pma.replay_buffer import Experience, StateAction

SelectionCriterion = Literal["thompson", "evb"]
SRPolicy = Literal["thomson_sampling", "q_means", "greedy"]


class ReplaySamplerAgent(object):
    """Generates and prioritizes simulated replays from Bayesian posteriors.

    Args:
        q_model: BayesianQLearning agent holding the Normal-Gamma posterior
            over Q(s, a) for every state-action pair.
        transition_model: DirichletTransitionsModel holding the Dirichlet
            posterior over T(s'|s, a) for every state-action pair.
        need_from_position: if True, compute need based on `agent_real_state`
            (the agent's actual position in the environment, distinct from
            the simulated tree-search's current node); if False, compute
            need averaged over the entire state space.
        selection: 'thompson' to prioritize candidates by sampling once from
            each posterior and acting on the sample, or 'evb' to prioritize
            by Expected Value of Backup (Gain x Need).
        H: simulation time budget — max number of simulated steps/backups
            per planning bout.
        agent_real_state: the agent's actual current state in the real
            environment (not the simulated search tree's position). Only
            used when `need_from_position` is True.
        SR_policy: which policy induces the on-policy successor
            representation used for the Need term — 'thomson_sampling'
            (Monte Carlo P(a is best) from the Q-posteriors), 'q_means'
            (softmax over posterior mean Q-values), or 'greedy' (one-hot
            over argmax posterior mean Q-values).
        valid_states: boolean array of shape (n_states,), True for states
            the agent can actually occupy (e.g. non-wall cells). States
            marked False are masked out of every EVB-based selection —
            compute_all_evb forces their row to a large negative sentinel
            so sample_tree_node's softmax gives them exactly zero
            probability of being picked as a fresh root. Left at its
            default (None), every state is treated as valid.
            Masking root selection alone is enough: if the transition
            model also assigns exactly zero probability to landing on an
            invalid state (as it should, since it's unreachable), an
            invalid state can then never become the search tree's current
            node via forward/backward expansion either — only via root
            sampling, which this closes off. Do NOT use `-inf` for the
            sentinel: expected_next_state_evb/expected_prev_state_evb
            multiply all_s_a_evb elementwise against a transition
            probability that is legitimately exactly 0 at an unreachable
            destination, and 0 * -inf = nan.

    Attributes:
        search_tree: simulated trajectories explored so far this bout, reset
            at the start of each `plan`-style call (analogous to PMAagent's
            `_chain`, generalized to a tree rather than a single chain).
        replays: accumulated log of executed simulated replays, as
            `Experience` tuples.
    """

    def __init__(
        self,
        q_model: BayesianQLearning,
        transition_model: DirichletTransitionsModel,
        need_from_position: bool = False,
        selection: SelectionCriterion = "evb",
        H: int = 1,
        agent_real_state: int = 0,
        SR_policy: SRPolicy = "greedy",
        valid_states: np.ndarray | None = None,
    ):
        self.q_model = q_model
        self.transition_model = transition_model
        self.need_from_position = need_from_position
        self.selection = selection
        self.H = H
        self.agent_real_state = agent_real_state
        self.SR_policy = SR_policy
        self.valid_states = valid_states
        self.search_strategies = ["root", "forward", "backward"]


    def sample_replay(self, H: int = None, temp: float = 1.0, return_logs: bool = False):
        if H is None:
            H = self.H
        search_tree = []
        replay_sequences = []
        sequences_strategy = []
        tree_strategy = []
        search_strategy = "root"
        logs = {"NREVB": [], "FEVB": [], "BEVB": []} if return_logs else None

        # Built once, up front: neither q_model nor transition_model changes
        # while sampling simulated replay, so every EVB query this bout can
        # share the same successor representation / stationary distribution.
        sr, stationary_dist = self._successor_representation(temp)
        all_s_a_evb = self.compute_all_evb(self.q_model, self.transition_model, sr, stationary_dist)
        # Also invariant for the bout: P(a'|s') for every s', used by both
        # expected_next_state_evb and expected_prev_state_evb. Sharing one
        # draw here avoids two independent (and differently noisy) Monte
        # Carlo re-estimates of the same quantity on every H-loop iteration.
        action_probs_grid = np.array([
            self.q_model.thomsom_sampling_probs(s_prime) for s_prime in range(self.q_model.n_states)
        ])

        for h in range(H):
            if len(search_tree) == 0:
                # Sample transition based on EVB using a softmax
                s, a = sample_tree_node(all_s_a_evb, temp=temp)
                search_tree.append(StateAction(s, a))
                tree_strategy.append(search_strategy)
                if return_logs:
                    logs["NREVB"].append(np.nan)
                    logs["FEVB"].append(np.nan)
                    logs["BEVB"].append(np.nan)
            else:
                current_state = search_tree[-1].state
                current_action = search_tree[-1].action
                # States already in this tree: forward/backward candidates
                # landing back on one of these are excluded below, so a
                # single tree never revisits a state.
                visited_states = [sa.state for sa in search_tree]
                # Compute expected EVB for all state action pairs that are not the last node in the tree
                pre_average_evb = np.copy(all_s_a_evb)
                pre_average_evb[current_state, current_action] = np.nan
                # New root EVB (NREVB): expectation under the same softmax(EVB, temp)
                candidate_evb = pre_average_evb[~np.isnan(pre_average_evb)]
                root_weights = softmax_weights(candidate_evb, temp=temp)
                NREVB = np.sum(root_weights * candidate_evb)

                # Compute expected next state EVB (Forward search)
                FEVB, FT_prob, F_action_prob = expected_next_state_evb(self.q_model, self.transition_model,
                                                                       current_state, current_action, all_s_a_evb,
                                                                       action_probs_grid)

                # Compute expected previous state EVB (Backward search)
                BEVB, BT_prob, B_action_prob = expected_prev_state_evb(self.q_model, self.transition_model,
                                                                       current_state, current_action, all_s_a_evb,
                                                                       action_probs_grid)

                if return_logs:
                    logs["NREVB"].append(NREVB)
                    logs["FEVB"].append(FEVB)
                    logs["BEVB"].append(BEVB)

                # We selected new root, forward or backward based on their respective EVB values
                if search_strategy == "root":
                    search_strategy = self.search_strategies[sample_from_boltzmann(np.array([NREVB, FEVB, BEVB]), temp=temp)]
                elif search_strategy == "forward":
                    search_strategy = self.search_strategies[sample_from_boltzmann(np.array([NREVB, FEVB, -1e6]), temp=temp)]
                elif search_strategy == "backward":
                    search_strategy = self.search_strategies[sample_from_boltzmann(np.array([NREVB, -1e6, BEVB]), temp=temp)]

                def flush_tree():
                    nonlocal search_tree, tree_strategy, search_strategy
                    replay_sequences.append(search_tree)
                    sequences_strategy.append(tree_strategy)
                    tree_strategy = []
                    search_tree = []
                    search_strategy = "root"

                if search_strategy == "root":
                    flush_tree()

                elif search_strategy == "forward":
                    next_state_action_probs = (FT_prob * F_action_prob).copy()
                    # Clause 1: never land on a state already in this tree.
                    next_state_action_probs[visited_states, :] = 0.0
                    # Clause 2: don't attach an action that would (on the
                    # next forward step) walk right back into an
                    # already-visited state -- e.g. a boundary/self-loop
                    # bump, or doubling back the way we came. The
                    # transition model is seeded near-deterministically, so
                    # its argmax is a cheap, accurate stand-in for "the
                    # state this (s, a) actually leads to."
                    dominant_next_state = self.transition_model.alpha.argmax(axis=-1)
                    next_state_action_probs[np.isin(dominant_next_state, visited_states)] = 0.0

                    total = next_state_action_probs.sum()
                    if total <= 0.0:
                        # No legal, non-repeating continuation -- abandon this tree.
                        flush_tree()
                    else:
                        next_state_action_probs = (next_state_action_probs / total).ravel()
                        new_state_action_index = np.random.choice(next_state_action_probs.size, p=next_state_action_probs)
                        new_state, new_action = self.state_action_from_index(new_state_action_index)
                        search_tree.append(StateAction(new_state, new_action))
                        tree_strategy.append(search_strategy)

                elif search_strategy == "backward":
                    prev_state_action_probs = (BT_prob * B_action_prob).copy()
                    # Never re-add a predecessor state already in this tree.
                    # (No clause-2 analog here: expected_prev_state_evb
                    # doesn't use the action at all -- BT_prob/B_action_prob
                    # only describe *this* predecessor, not what a further
                    # backward step from it would do.)
                    prev_state_action_probs[visited_states, :] = 0.0

                    total = prev_state_action_probs.sum()
                    if total <= 0.0:
                        flush_tree()
                    else:
                        prev_state_action_probs = (prev_state_action_probs / total).ravel()
                        prev_state_action_index = np.random.choice(prev_state_action_probs.size, p=prev_state_action_probs)
                        prev_state, prev_action = self.state_action_from_index(prev_state_action_index)
                        search_tree.append(StateAction(prev_state, prev_action))
                        tree_strategy.append(search_strategy)

        # If there is a search tree, include to replay sequence
        if len(search_tree) > 0:
            replay_sequences.append(search_tree)
            sequences_strategy.append(tree_strategy)
        if return_logs:
            return replay_sequences, sequences_strategy, logs
        return replay_sequences, sequences_strategy

    def state_action_from_index(self, index: int) -> tuple[int, int]:
        """Inverse of raveling an (n_states, n_actions) array: flat index -> (state, action)."""
        s, a = np.unravel_index(index, (self.q_model.n_states, self.q_model.n_actions))
        return int(s), int(a)

    def _sr_policy_probs(self, state: int, temp: float) -> np.ndarray:
        """Action-probability row for `state` under `self.SR_policy`.

        Feeds the on-policy transition matrix that the successor
        representation is built from — see `_successor_representation`.
        """
        q_means = self.q_model.q_means(state)
        if self.SR_policy == "thomson_sampling":
            return self.q_model.thomsom_sampling_probs(state)
        elif self.SR_policy == "q_means":
            return softmax_weights(q_means, temp=temp)
        elif self.SR_policy == "greedy":
            probs = np.zeros(self.q_model.n_actions)
            probs[np.argmax(q_means)] = 1.0
            return probs
        raise ValueError(f"Unknown SR_policy {self.SR_policy!r}")

    def _successor_representation(self, temp: float) -> tuple[np.ndarray, np.ndarray]:
        """Build SR(s, s') and the on-policy stationary distribution, once
        for the whole `sample_replay` bout.

        Neither q_model nor transition_model is updated while sampling
        simulated replay, so a single successor representation and
        stationary distribution (both under `self.SR_policy`) are valid
        for every EVB query made during the bout — no need to rebuild
        them per state-action pair.

        Mattar & Daw (2018) Online Methods, "Need term": Need(sk) is the
        nth row of SR = (I - gamma*T_pi)^-1 when the agent's current
        state n is known, or the stationary distribution mu (mu @ T_pi =
        mu) when it isn't (e.g. during sleep, used here for
        need_from_position=False). The stationary distribution isn't
        recoverable from SR alone, so T_pi is duplicated here from
        DirichletTransitionsModel.successor_representation.
        """
        policy_probs = np.array([
            self._sr_policy_probs(s, temp) for s in range(self.q_model.n_states)
        ])
        gamma = self.q_model.gamma
        sr = self.transition_model.successor_representation(gamma, policy_probs)

        mean_t = self.transition_model.alpha / self.transition_model.alpha.sum(axis=-1, keepdims=True)
        t_pi = np.einsum("sa,sap->sp", policy_probs, mean_t)
        stationary_dist = self._stationary_distribution(t_pi)

        return sr, stationary_dist

    @staticmethod
    def _stationary_distribution(t_pi: np.ndarray, n_iter: int = 10_000) -> np.ndarray:
        """Cesaro-averaged occupancy of t_pi starting from a uniform distribution:
        mu = mean over k=0..n_iter-1 of (uniform @ t_pi^k).

        A direct linear solve for "mu such that mu @ t_pi = mu" (replacing
        one row of the homogeneous system with the normalization
        constraint) only has a unique solution when t_pi is irreducible --
        true when every (s, a) had some residual transition probability
        everywhere, but not once transitions became exact one-hot: under a
        deterministic policy (e.g. SR_policy="greedy") and deterministic
        transitions, t_pi is a deterministic functional graph, which
        generically splits into multiple disjoint cycles (a singular
        system -- LinAlgError) and/or is periodic (plain power iteration
        would oscillate rather than converge). Cesaro-averaging from a
        uniform start sidesteps both: it's always well-defined (no matrix
        inversion), converges even for periodic/reducible chains, and its
        "expected occupancy averaged over every possible starting state"
        reading is exactly what need_from_position=False's docstring asks
        for -- arguably a better match than picking one arbitrary member of
        a non-unique solution set when the chain isn't irreducible anyway.
        """
        n = t_pi.shape[0]
        mu = np.full(n, 1.0 / n)
        mu_sum = np.zeros(n)
        for _ in range(n_iter):
            mu_sum += mu
            mu = mu @ t_pi
        return mu_sum / n_iter

    def compute_all_evb(
        self,
        q_model: BayesianQLearning,
        transition_model: DirichletTransitionsModel,
        sr: np.ndarray,
        stationary_dist: np.ndarray,
    ) -> np.ndarray:
        """EVB(s, a) for every state-action pair, reusing the precomputed `sr`/`stationary_dist`."""
        evb = np.empty((q_model.n_states, q_model.n_actions))
        for s in range(q_model.n_states):
            means = q_model.q_means(s)  # computed once per state, not once per (state, action)
            for a in range(q_model.n_actions):
                evb[s, a] = self.compute_single_evb(q_model, transition_model, s, a, sr, stationary_dist, means=means)
        if self.valid_states is not None:
            # Large finite sentinel, not -inf: forward/backward sampling
            # multiplies this elementwise against a transition probability
            # that's legitimately exactly 0 at an unreachable destination,
            # and 0 * -inf = nan. -1e6 already underflows softmax to exact
            # 0 probability at this EVB scale (matches the masking sentinel
            # used for the root/forward/backward strategy gate in
            # sample_replay).
            evb[~self.valid_states, :] = -1e6
        return evb

    def compute_single_evb(
        self,
        q_model: BayesianQLearning,
        transition_model: DirichletTransitionsModel,
        s: int,
        a: int,
        sr: np.ndarray,
        stationary_dist: np.ndarray,
        means: np.ndarray | None = None,
    ) -> float:
        """EVB(s, a) = VPI(s, a) * Need(s, a).

        VPI comes straight from the Q-posterior. Need follows Mattar & Daw
        (2018): SR(agent_real_state, s) — the nth row of the SR matrix,
        where n is the agent's real current state — if `need_from_position`,
        else the on-policy stationary distribution at s (their "sleep"
        alternative, used when no single current position anchors Need).

        `means` (q_model.q_means(s)) can be passed in by a caller looping
        over every action at the same state, so it isn't rebuilt on every
        call — see compute_all_evb.
        """
        vpi = q_model.vpi(s, a, means=means)
        if self.need_from_position:
            need = float(sr[self.agent_real_state, s])
        else:
            need = float(stationary_dist[s])
        return vpi * need


def expected_next_state_evb(
    q_model: BayesianQLearning,
    transition_model: DirichletTransitionsModel,
    s: int,
    a: int,
    all_s_a_evb: np.ndarray,
    action_probs_grid: np.ndarray,
) -> tuple[float, np.ndarray, np.ndarray]:
    """FEVB(s, a) = sum_{a'} sum_{s'} T(s'|s, a) P(a'|s') EVB(s', a').

    T(s'|s, a) is the Dirichlet posterior mean transition probability.
    P(a'|s') is `action_probs_grid` — the Thompson-sampling P(a is best)
    estimate from q_model for every s', computed once at the top of
    `sample_replay` and shared with expected_prev_state_evb (rather than
    redrawn here every call, which would both waste the Monte Carlo work
    and give forward/backward two independently-noisy estimates of what
    should be the same quantity). EVB(s', a') is read from `all_s_a_evb`
    (also computed once at the top of `sample_replay`) rather than
    recomputed here from VPI/Need.

    Returns (FEVB, FT_prob, F_action_prob): FT_prob is T(s'|s, a) shaped
    (n_states, 1) so it broadcasts correctly against F_action_prob
    (n_states, n_actions) — both a joint (s', a') distribution for the
    caller to sample from, and the terms of the FEVB sum itself.
    """
    ft_prob = transition_model.mean_transition_probs(s, a)[:, None]  # (n_states, 1)
    f_action_prob = action_probs_grid  # (n_states, n_actions)

    fevb = float(np.sum(ft_prob * f_action_prob * all_s_a_evb))
    return fevb, ft_prob, f_action_prob

def expected_prev_state_evb(
    q_model: BayesianQLearning,
    transition_model: DirichletTransitionsModel,
    s: int,
    a: int,
    all_s_a_evb: np.ndarray,
    action_probs_grid: np.ndarray,
) -> tuple[float, np.ndarray, np.ndarray]:
    """BEVB(s, a) = sum_{a'} sum_{s'} T(s|s', a') P(a'|s') EVB(s', a').

    `action_probs_grid` is the same P(a'|s') term as expected_next_state_evb
    (Thompson-sampling P(a is best) from q_model), shared rather than
    redrawn here — that part genuinely is a mirror image of the forward
    case. T(s|s', a') is not, though: in the forward case
    T(s'|s, a) is a single row lookup (one Dirichlet posterior, the
    current (s, a)'s own distribution over successors). Here every
    candidate predecessor (s', a') has its *own* distribution, and we
    need the probability mass each of those distributions places on
    THIS state s — i.e. one column, gathered across every (s', a'), out
    of the full (n_states, n_actions, n_states) transition tensor. So
    "inverse traversal" holds at the level of the overall formula
    (predecessors weighted by [transition-into-s] x [action prob at
    predecessor] x EVB, mirroring successors weighted by
    [transition-out-of-s] x [action prob at successor] x EVB), but not
    as a literal code transpose of expected_next_state_evb — the T term
    requires a different, more expensive lookup.

    `a` does not appear in the RHS of the formula above (T(s|s', a')
    only depends on the state you're looking backward from, not the
    action you'll take there), so it's unused here — kept only so this
    function's signature matches expected_next_state_evb's at the
    sample_replay call site.
    """
    mean_t = transition_model.alpha / transition_model.alpha.sum(axis=-1, keepdims=True)  # (n_states, n_actions, n_states)
    bt_prob = mean_t[:, :, s]  # (n_states, n_actions): T(s | s', a') for every predecessor (s', a')

    b_action_prob = action_probs_grid  # (n_states, n_actions): P(a'|s') for every s'

    bevb = float(np.sum(bt_prob * b_action_prob * all_s_a_evb))
    return bevb, bt_prob, b_action_prob


def softmax_weights(values: np.ndarray, temp: float = 1.0) -> np.ndarray:
    """Numerically stable softmax(values / temp); values must contain no NaNs."""
    shifted = (values - np.max(values)) / temp
    weights = np.exp(shifted)
    return weights / weights.sum()


def sample_tree_node(all_s_a_evb: np.ndarray, temp: float = 1.0) -> tuple[int, int]:
    """Sample a new root (s, a), weighted by softmax(EVB, temp) over every pair."""
    flat_evb = all_s_a_evb.ravel()
    weights = softmax_weights(flat_evb, temp=temp)
    index = np.random.choice(flat_evb.size, p=weights)
    s, a = np.unravel_index(index, all_s_a_evb.shape)
    return int(s), int(a)

def sample_from_boltzmann(values: np.ndarray, temp: float = 1.0) -> int:
    """Sample an index from softmax(values, temp). `values` are raw scores, not probabilities."""
    weights = softmax_weights(values, temp=temp)
    return int(np.random.choice(values.size, p=weights))