"""Bayesian prioritized replay sampler.

Combines a Normal-Gamma posterior over Q(s, a) (Dearden, Friedman & Russell
1998) with a Dirichlet posterior over transitions T(s'|s, a) (Dearden,
Friedman & Andre 1999) to drive simulated replay: rather than replaying only
transitions actually observed, candidate (s, a, s') backups are generated by
sampling from the agent's own uncertainty about the world, and prioritized
either by Thompson sampling or by Expected Value of Backup (Mattar & Daw
2018).
"""
from __future__ import annotations

from typing import Literal
import numpy as np

from unc_pma.bayesian_qlearning import BayesianQLearning
from unc_pma.environment_model import DirichletTransitionsModel
from unc_pma.replay_buffer import Experience, StateAction

SelectionCriterion = Literal["thompson", "evb"]


class ReplaySamplerAgent(object):
    """Generates and prioritizes simulated replays from Bayesian posteriors.

    Args:
        q_model: BayesianQLearning agent holding the Normal-Gamma posterior
            over Q(s, a) for every state-action pair.
        transition_model: DirichletTransitionsModel holding the Dirichlet
            posterior over T(s'|s, a) for every state-action pair.
        need_from_position: if True, compute need based on the current position
            in the state space; if False, compute need based on the entire
            state space.
        selection: 'thompson' to prioritize candidates by sampling once from
            each posterior and acting on the sample, or 'evb' to prioritize
            by Expected Value of Backup (Gain x Need).
        H: simulation time budget — max number of simulated steps/backups
            per planning bout.

    Attributes:
        search_tree: simulated trajectories explored so far this bout, reset
            at the start of each `plan`-style call (analogous to PMAagent's
            `_chain`, generalized to a tree rather than a single chain).
        replays: accumulated log of executed simulated replays, as
            `Experience` tuples.
    """

    def __init__(
        self,
        q_model: BayesianQLearning,
        transition_model: DirichletTransitionsModel,
        need_from_position: bool = False,
        selection: SelectionCriterion = "evb",
        H: int = 1,
    ):
        self.q_model = q_model
        self.transition_model = transition_model
        self.need_from_position = need_from_position
        self.selection = selection
        self.H = H
        self.search_strategies = ["root", "forward", "backward"]


    def sample_replay(self, H: int = None, temp: float = 1.0):
        if H is None:
            H = self.H
        search_tree = []
        replay_sequences = []
        search_strategy = "root"

        all_s_a_evb = compute_all_evb(self.q_model, self.transition_model)
        for h in range(H):
            if len(search_tree) == 0:
                # Sample transition based on EVB using a softmax
                s, a = sample_tree_node(all_s_a_evb)
                search_tree.append(StateAction(s, a))
            else:
                current_state = search_tree[-1].state
                current_action = search_tree[-1].action
                # Compute expected EVB for all state action pairs that are not the last node in the tree
                pre_average_evb = np.copy(all_s_a_evb)
                pre_average_evb[current_state, current_action] = np.nan
                # New root EVB (NREVB)
                NREVB = np.nanmean(pre_average_evb)

                # Compute expected next state EVB (Forward search)
                FEVB = expected_next_state_evb(self.q_model, self.transition_model, current_state, current_action)

                # Compute expected previous state EVB (Backward search)
                BEVB = expected_prev_state_evb(self.q_model, self.transition_model, current_state, current_action)

                # We selected new root, forward or backward based on their respective EVB values
                if search_strategy == "root":
                    search_strategy = self.search_strategies[sample_from_boltzmann(np.array([NREVB, FEVB, BEVB]), temp=temp)]
                elif search_strategy == "forward":
                    search_strategy = self.search_strategies[sample_from_boltzmann(np.array([NREVB, FEVB, -1e5]), temp=temp)]
                elif search_strategy == "backward":
                    search_strategy = self.search_strategies[sample_from_boltzmann(np.array([NREVB, -1e5, BEVB]), temp=temp)]

                if search_strategy == "root":
                    replay_sequences.append(search_tree)
                    search_tree = []

                elif search_strategy == "forward":
                    next_state_probs = self.transition_model.mean_transition_probs(current_state, current_action)



def expected_next_state_evb(all_s_a_evb, transition_model: DirichletTransitionsModel, s: int, a: int):
    # get all next state probabilities from transition model
    P = transition_model.mean_transition_probs(s, a)  # Potential next states # S x A
    return np.mean(all_s_a_evb * P)

def expected_prev_state_evb(all_s_a_evb: np.ndarray, transition_model: DirichletTransitionsModel, s: int, a: int):
    # Hi claude check this one, I'm not sure how to implement it
    pass


def compute_all_evb(q_model: BayesianQLearning, transition_model: DirichletTransitionsModel):
    # Returns an array of EVB for all state-action pairs in the environment
    pass

def compute_single_evb(q_model: BayesianQLearning, transition_model: DirichletTransitionsModel, s: int, a: int):
    # Returns the EVB for a single state-action pair (s, a)
    # If we don't have next state, we can take expectation over the next state
    # Need would be Successor representation from transition model. SR(s, s')
    pass


def sample_tree_node(all_s_a_evb: np.ndarray, temp: float = 1.0):
    # Return s, a with weight probability based on softmax of their evb
    pass

def sample_from_boltzmann(values: np.ndarray, temp: float = 1.0):
    # Return index sampled from softmax of values
    pass